save_intermediate_files: false
input_dir: 'speech_examples_small'


file_mapper:
  file_mapper:


encoding_converter:
  wav_converter:
#    input_dir: 'speech_examples_small'
    output_dir: 'convert_preprocessed'

voice_music_separator:
  ina_speech_segmenter:
#    input_dir: 'convert_preprocessed'
    output_dir: 'ina_preprocessed'
    filtered_dir: 'ina_filtered'
    vad_engine: 'sm'

embedding:
  pyannote_embedding:
#    input_dir: 'ina_preprocessed'
    sliding_window_duration: 3.0
    sliding_window_step: 1.0

speaker_classifier:
  common_voices_gender:
    input_dir: 'ina_preprocessed'
    embedding: 'pyannote'
    sliding_window_duration: 3.0
    sliding_window_step: 1.0