save_intermediate_files: false
input_dir: 'speech_examples_small'


file_mapper:
  file_mapper:


encoding_converter:
  wav_converter:
    output_dir: 'convert_preprocessed'

voice_music_separator:
  ina_speech_segmenter:
    output_dir: 'ina_preprocessed'
    filtered_dir: 'ina_filtered'
    vad_engine: 'sm'

embedding:
  pyannote_embedding:
    sliding_window_duration: 3.0
    sliding_window_step: 1.0

segment_classifier:
  common_voices_gender:
    classification_column_name: 'common_voices_gender_classification'
    verbal_labels: true

  common_voices_age:
    classification_column_name: 'common_voices_age_classification'
    verbal_labels: true
