save_intermediate_files: true  # TODO: not implemented
input_dir: 'speech_examples_small'

preprocessing:
  file_mapper:
  wav_converter:
    output_dir: 'convert_preprocessed'
  ina_speech_segmenter:
    output_dir: 'ina_preprocessed'
    filtered_dir: 'ina_filtered'
    vad_engine: 'sm'

feature_extraction:
  pyannote_embedding:
    sliding_window_duration: 3.0
    sliding_window_step: 1.0

segment_classifier:
  common_voices_gender:
    pretrained_models_dir: 'pretrained_models/common_voice'
    classification_column_name: 'common_voices_gender_classification'
    verbal_labels: true

  common_voices_age:
    pretrained_models_dir: 'pretrained_models/common_voice'
    classification_column_name: 'common_voices_age_classification'
    verbal_labels: true

  speech_brain_iemocap_emotion:
    pretrained_models_dir: 'pretrained_models/speech_brain_iemocap_emotion'
    classification_column_name: 'speech_brain_iemocap_emotion'
    verbal_labels: true
