params:
  clustering:
    method: centroid
    min_cluster_size: 13
    threshold: 0.71
  segmentation:
    min_duration_off: 0.1
    threshold: 0.6
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: speechbrain/spkrec-ecapa-voxceleb
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: pyannote/segmentation@2022.07
    segmentation_batch_size: 32
